/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject1;

import com.mongodb.BasicDBObject;
import com.mongodb.BulkWriteOperation;
import com.mongodb.BulkWriteResult;
import com.mongodb.Cursor;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import com.mongodb.ParallelScanOptions;
import com.mongodb.ServerAddress;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author leo7l
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
        MongoClient mongoClient = new MongoClient("localhost", 27017);
        DB db = mongoClient.getDB( "admin" );;
        //db = mongoClient.getDB( "admin" );
        DBCollection coll = db.getCollection("Usuários");
        Cadastro cad = new Cadastro();
//        App login = new App();
    
    public App() {
        initComponents();
        MongoClient mongoClient = new MongoClient("localhost", 27017);
        DB db;
        db = mongoClient.getDB( "admin" );
        DBCollection coll = db.getCollection("Usuários");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmailLabel = new javax.swing.JLabel();
        EmailText = new javax.swing.JTextField();
        SenhaLabel = new javax.swing.JLabel();
        SenhaText = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        CadButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EmailLabel.setText("Email");

        SenhaLabel.setText("Senha");

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        CadButton.setText("Cadastro");
        CadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SenhaLabel)
                            .addComponent(EmailLabel)
                            .addComponent(EmailText)
                            .addComponent(SenhaText, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(LoginButton)
                        .addGap(18, 18, 18)
                        .addComponent(CadButton)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(EmailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SenhaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SenhaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginButton)
                    .addComponent(CadButton))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
         // TODO add your handling code here:
        //MongoClient mongoClient = new MongoClient("localhost", 27017);
        //DB db;
       // db = mongoClient.getDB( "admin" );
        //DBCollection coll = db.getCollection("Usuários");
        DBObject i;
        
        BasicDBObject busca = new BasicDBObject();
        
        busca.put("email",EmailText.getText());
        busca.put("senha",SenhaText.getText());
        i = coll.findOne(busca);
        if(i != null){
            
            JOptionPane.showMessageDialog(null, "Você logou!");
        }else{
            BasicDBObject doc = new BasicDBObject("email", EmailText.getText())
            .append("senha", SenhaText.getText())
            .append("nome", " ")
            .append("cpf"," ");
            coll.insert(doc);
            JOptionPane.showMessageDialog(null,"Usuario Criado");
        }
        
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void CadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadButtonActionPerformed
        // TODO add your handling code here:
        
       // cad.setVisible(true);
       //login.setVisible(false);
    }//GEN-LAST:event_CadButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*MongoClient mongoClient = new MongoClient("localhost", 27017);
        DB db;
        db = mongoClient.getDB( "admin" );
        DBCollection coll = db.getCollection("Usuários");*/
        
        /*BasicDBObject doc = new BasicDBObject("email", "leo99lindoso")
        .append("senha", "123")
        .append("nome", "leozin")
        .append("cpf",123456789);
        coll.insert(doc);*/
        
        //JFrame frame = new JFrame("App");
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*MongoClient mongoClient = new MongoClient("localhost", 27017);
        DB db;
        db = mongoClient.getDB( "admin" );
        DBCollection coll = db.getCollection("Usuários");*/
        
        /*BasicDBObject doc = new BasicDBObject("email", "leo99lindoso")
        .append("senha", "123")
        .append("nome", "leozin")
        .append("cpf",123456789);
        coll.insert(doc);*/
        
        //JFrame frame = new JFrame("App");
        

        //System.out.print(db);
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadButton;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailText;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel SenhaLabel;
    private javax.swing.JPasswordField SenhaText;
    // End of variables declaration//GEN-END:variables
}
